###
POST http://localhost:8080/api/customer
Content-Type: application/json

{
  "customerName": "John Doe",
  "customerEmail": "johndoe@example.com",
  "customerPassword": "password123"
}

###
POST http://localhost:8080/api/discountRule
Content-Type: application/json

{
  "itemQuantity": 1,
  "discountRate": 50
}


###
POST http://localhost:8080/api/discountRule
Content-Type: application/json

{
  "itemQuantity": 2,
  "discountRate": 60
}

###
POST http://localhost:8080/api/product
Content-Type: application/json

{"productName": "food",
  "productPrice": 100,
  "stockQuantity": 100}

###
POST http://localhost:8080/api/productDiscountPref
Content-Type: application/json

{"productId": 1,
  "discountRuleId": 1
}

###
POST http://localhost:8080/api/productDiscountPref
Content-Type: application/json

{"productId": 1,
  "discountRuleId": 2
}

###
POST http://localhost:8080/api/cartProduct/1/2

###
GET http://localhost:8080/api/product/all
